-- AlterTable
ALTER TABLE `EventFeedback` ADD COLUMN `additionalComments` VARCHAR(191) NULL,
    ADD COLUMN `b2bMeetings` INTEGER NULL,
    ADD COLUMN `companyAddress` VARCHAR(191) NULL,
    ADD COLUMN `companyName` VARCHAR(191) NULL,
    ADD COLUMN `competitorMarketingMethods` VARCHAR(191) NULL,
    ADD COLUMN `contactNumber` VARCHAR(191) NULL,
    ADD COLUMN `contactPerson` VARCHAR(191) NULL,
    ADD COLUMN `continueFairParticipation` BOOLEAN NULL,
    ADD COLUMN `existingCustomers` INTEGER NULL,
    ADD COLUMN `expectedOrders` DECIMAL(15, 2) NULL,
    ADD COLUMN `hadUnmaterializedInquiries` BOOLEAN NULL,
    ADD COLUMN `improvementSuggestions` VARCHAR(191) NULL,
    ADD COLUMN `majorCompetitors` VARCHAR(191) NULL,
    ADD COLUMN `newContacts` INTEGER NULL,
    ADD COLUMN `ordersBooked` DECIMAL(15, 2) NULL,
    ADD COLUMN `problemsFaced` VARCHAR(191) NULL,
    ADD COLUMN `productsExhibited` VARCHAR(191) NULL,
    ADD COLUMN `satisfactionLevel` VARCHAR(191) NULL,
    ADD COLUMN `tdapRecommendations` VARCHAR(191) NULL,
    ADD COLUMN `unmaterializedReasons` VARCHAR(191) NULL,
    ADD COLUMN `visitorsCountries` VARCHAR(191) NULL;
